### ISSUE TITLE
grunt-galvanize not found

### ISSUE THREAD

**Issue by rwlaschin** [dylancwood/grunt-galvanize#1]
It would be nice if this conformed to the standard require(''grunt-<name>').  
Currently I have to do the following: require('./node_modules/grunt-galvanize/tasks/galvanize.js')(grunt);

Please fix.

**Comment by dylancwood** [comment]
Sorry for the delay in getting back to you on this.

Thanks for pointing this out. I will get it fixed right away.

**Comment by dylancwood** [comment]
I've added a `main` entry point to _package.json_. That should instruct the node `require` module to find the task within `grunt-load-tasks`.

Let  me know if it works for you.

**Comment by dylancwood** [comment]
Feel free to reopen this if you are still having trouble @rwlaschin
