### ISSUE TITLE
Cant pull value from galvanize config

### ISSUE THREAD

**Issue by chris-hinds** [dylancwood/grunt-galvanize#3]
Hi, I have stumbled across your Grunt-Galvanize which seems to solve my issue (need to run a task multiple times with different values)

So I have galvanize in and working, in the fact that my task loops for the numbers of objects within the array of config objects. However I am unable to retrieve the value from the galvanize config when running the task.

I want to be able to use a value from the config as part of a path string so the task runs against different paths each time.

This is my grunt file:

```
/*global module:false*/
module.exports = function(grunt) {
    var LIVERELOAD_PORT = 35729;
    var config = [
            { configs: {color: 'red'}, options: {size: 'small'} },
            { configs: {color: 'green'}, options: {size: 'small'} }
        ];

    // Project configuration.
    grunt.initConfig({
        // Metadata.
        pkg: grunt.file.readJSON('package.json'),
        purifycss: {
            options: {
                minify: true,
            },
            target: {
                src: ['../src/components/article/templates/article_dev.mustache'],
                css: ['../src/components/lib/templates/' + grunt.config.color + '/index.mustache'],
                dest: '../src/components/lib/templates/' + grunt.config.color + '/index.mustache'
            }   
        },
    });

    grunt.loadNpmTasks('grunt-purifycss');
    grunt.loadNpmTasks('grunt-galvanize');

    grunt.registerTask('mytask', 'This is a task which runs taskName', function() {
        grunt.option('galvanizeConfig', config);
        console.log(grunt.config.color)

        grunt.task.run(['galvanize:purifycss']);
    });
};`
```
So inside the `purifycss` task you can see I have tried to access `grunt.config.color` this always returns `undefined`

**Comment by rkoya** [comment]
I have the same issue, did you manage to find a solution?

**Comment by chris-hinds** [comment]
Hi, I did find the solution yes, Just on my way home from work. I will update this thread with what i found later on.

**Comment by rkoya** [comment]
Many thanks a solution would be much appreciated, spent a while now trying to figure this out but still getting undefined, and not much out there in terms of use of galvanize.

**Comment by chris-hinds** [comment]
this is what worked for me: `<%= grunt.config(\'color\') %>`

**Comment by rkoya** [comment]
Many thanks that worked perfectly!!

**Comment by dylancwood** [comment]
I am glad that you sorted this out. Thank you @hindsc52 for sharing your solution.
