### ISSUE TITLE
When will the latest changes be released to npm 

### ISSUE THREAD

**Issue by MarcelloDiSimone** [dylancwood/grunt-galvanize#4]
The latest changes to the project are not included in the package that you get when installing with npm. More specific the changed handling of grunt task targets called by galvanize. 

For example running this:
`grunt.task.run(['galvanize:express:default:stop']);`

npm version runs express:default`

github version runs express:default:stop **correctly as expected**

Is there any chance those changes will be published anytime soon? I'm asking because installing your module via github directly don't works, due to a typo in your package.json. There your project name is defined and installed as: 

grunt-galv**e**nize

not 

grunt-galv**a**nize

BTW: Really love your plugin, helped me tremendously in my current project. Thanks

**Comment by dylancwood** [comment]
Hi Marcello,

I have published v2.0.1 to npm under the name `grunt-galvanize`.

The major version bump is to mark the name-change from `grunt-galvenize` to `grunt-galvanize`. 

Thank you for pointing this spelling error out, and for your kind words about the repo.
